// <auto-generated />
using System;
using Imanol_Acosta_AP1_P2.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Imanol_Acosta_AP1_P2.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20250715005922_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Imanol_Acosta_AP1_P2.Models.Entrada", b =>
                {
                    b.Property<int>("EntradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntradaId"));

                    b.Property<double>("CantidadProducida")
                        .HasColumnType("float");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProducido")
                        .HasColumnType("int");

                    b.Property<double>("PesoTotal")
                        .HasColumnType("float");

                    b.Property<int?>("ProductoID")
                        .HasColumnType("int");

                    b.HasKey("EntradaId");

                    b.HasIndex("ProductoID");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("Imanol_Acosta_AP1_P2.Models.EntradaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Cantidad")
                        .HasColumnType("float");

                    b.Property<int>("EntradaId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntradaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("EntradaDetalles");
                });

            modelBuilder.Entity("Imanol_Acosta_AP1_P2.Models.Producto", b =>
                {
                    b.Property<int>("ProductoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EsCompuesto")
                        .HasColumnType("bit");

                    b.Property<double>("Existencia")
                        .HasColumnType("float");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.HasKey("ProductoID");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Imanol_Acosta_AP1_P2.Models.Entrada", b =>
                {
                    b.HasOne("Imanol_Acosta_AP1_P2.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoID");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Imanol_Acosta_AP1_P2.Models.EntradaDetalle", b =>
                {
                    b.HasOne("Imanol_Acosta_AP1_P2.Models.Entrada", "Entrada")
                        .WithMany()
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Imanol_Acosta_AP1_P2.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrada");

                    b.Navigation("Producto");
                });
#pragma warning restore 612, 618
        }
    }
}
